#!/bin/bash

echo "Black       \\033[0;30m     Dark Gray     \\033[1;30m"
echo "Red         \\033[0;31m     Light Red     \\033[1;31m"
echo "Green       \\033[0;32m     Light Green   \\033[1;32m"
echo "Brown       \\033[0;33m     Yellow        \\033[1;33m"
echo "Blue        \\033[0;34m     Light Blue    \\033[1;34m"
echo "Purple      \\033[0;35m     Light Purple  \\033[1;35m"
echo "Cyan        \\033[0;36m     Light Cyan    \\033[1;36m"
echo "Light Gray  \\033[0;37m     White         \\033[1;37m"

echo -e "\033[0;30mBlack       \\033[1;30m     Dark Gray     "
echo -e "\033[0;31mRed         \\033[1;31m     Light Red     "
echo -e "\033[0;32mGreen       \\033[1;32m     Light Green   "
echo -e "\033[0;33mBrown       \\033[1;33m     Yellow        "
echo -e "\033[0;34mBlue        \\033[1;34m     Light Blue    "
echo -e "\033[0;35mPurple      \\033[1;35m     Light Purple  "
echo -e "\033[0;36mCyan        \\033[1;36m     Light Cyan    "
echo -e "\033[0;37mLight Gray  \\033[1;37m     White         "
